### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by Mori-hub** [ygguorun/pot-app-recognize-plugin-ocrtex#1]
Hi Dear,
I followed your method but 
Could you, please, explain what do you mean:

    Download the plugin for your platform.
    After installation, enter the session_id.

Thank you

**Comment by ygguorun** [comment]
Apologies for the delayed response.

This project is a plugin developed in tandem with the [pot-desktop](https://github.com/pot-app/pot-desktop) software. To get started:

1. Begin by installing [pot-desktop](https://github.com/pot-app/pot-desktop) from the [pot-desktop releases](https://github.com/pot-app/pot-desktop/releases) page. Download the latest release compatible with your operating system and proceed with the installation.

2. After successfully installing pot-desktop, download the plugin tailored for your operating system from the [releases](https://github.com/ygguorun/pot-app-recognize-plugin-pix2text/releases).

3. Once you have the plugin downloaded, navigate to the `Service` option on the left sidebar of the pot-desktop software. In the `Recognize` tab on the right, click the `Add Extension` button to seamlessly integrate the plugin.

4. Following the plugin installation, click on its name, input the `session_id`, and, assuming everything is in order, you should be able to utilize its features.
![f22ca4da44538834496623cf13741bed](https://github.com/ygguorun/pot-app-recognize-plugin-pix2text/assets/36809814/ef855455-af5c-4e6a-823d-73addcb926fc)

Should you encounter any further issues, please don't hesitate to reply below. Best of luck!
